// Generated by CoffeeScript 1.11.1
var Response, Toffee, View;

Response = require('was/response');

Toffee = require('toffee');

View = {
  exampleName: function(req, env) {
    var exampleText, tmpl;
    exampleText = '\nenvironment: #{env.stage}\n';
    tmpl = Toffee.compileStr(exampleText);
    return new Response(tmpl, 200);
  }
};

export default View;
